export const songs = [
  { title: "1 last bye", name: "Kiran", source: "https://vi3e.pages.dev/Music/Songs/1 last bye - Kiran.mp3", cover: "https://vi3e.pages.dev/Music/Covers/1 last bye.jpg" },
  { title: "2 Hearts", name: "Sam Feldt", source: "https://vi3e.pages.dev/Music/Songs/2 Hearts - Sam Feldt.mp3", cover: "https://vi3e.pages.dev/Music/Covers/2 Hearts.jpg" },
  { title: "8 Letters", name: "Why Don't We", source: "https://vi3e.pages.dev/Music/Songs/8 Letters - Why Don't We.mp3", cover: "https://vi3e.pages.dev/Music/Covers/8 Letters.jpg" },
  { title: "10:35", name: "TiÃ«sto", source: "https://vi3e.pages.dev/Music/Songs/10_35 - TiÃ«sto.mp3", cover: "https://vi3e.pages.dev/Music/Covers/10_35.jpg" },
  { title: "2002", name: "Anne-Marie", source: "https://vi3e.pages.dev/Music/Songs/2002 - Anne-Marie.mp3", cover: "https://vi3e.pages.dev/Music/Covers/2002.jpg" },
  { title: "A Different Way", name: "DJ Snake", source: "https://vi3e.pages.dev/Music/Songs/A Different Way- DJ Snake.mp3", cover: "https://vi3e.pages.dev/Music/Covers/A Different Way.jpg" },
  { title: "A Thousand Years", name: "James Arthur", source: "https://vi3e.pages.dev/Music/Songs/A Thousand Years - James Arthur.mp3", cover: "https://vi3e.pages.dev/Music/Covers/A Thousand Years.jpg" },
  { title: "All About It", name: "Deep Chills", source: "https://vi3e.pages.dev/Music/Songs/All About It - Deep Chills.mp3", cover: "https://vi3e.pages.dev/Music/Covers/All About It.jpg" },
  { title: "All Falls Down", name: "Alan Walker", source: "https://vi3e.pages.dev/Music/Songs/All Falls Down - Alan Walker.mp3", cover: "https://vi3e.pages.dev/Music/Covers/All Falls Down.jpg" },
  { title: "All We Are", name: "Richello", source: "https://vi3e.pages.dev/Music/Songs/All We Are - Richello.mp3", cover: "https://vi3e.pages.dev/Music/Covers/All We Are.jpg" },
  { title: "All We Know", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/All We Know - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/All We Know.jpg" },
  { title: "Another Love", name: "Tom Odell", source: "https://vi3e.pages.dev/Music/Songs/Another Love - Tom Odell.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Another Love.jpg" },
  { title: "Bad Girl", name: "Daya", source: "https://vi3e.pages.dev/Music/Songs/Bad Girl - Daya.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Bad Girl.jpg" },
  { title: "Beach House", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/Beach House - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Beach House.jpg" },
  { title: "Beautiful Mistakes", name: "Maroon 5", source: "https://vi3e.pages.dev/Music/Songs/Beautiful Mistakes - Maroon 5.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Beautiful Mistakes.jpg" },
  { title: "Beautiful Now", name: "Zedd", source: "https://vi3e.pages.dev/Music/Songs/Beautiful Now - Zedd.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Beautiful Now.jpg" },
  { title: "Believers", name: "Alan Walker", source: "https://vi3e.pages.dev/Music/Songs/Believers - Alan Walker.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Believers.jpg" },
  { title: "Belong Together", name: "Mark Ambor", source: "https://vi3e.pages.dev/Music/Songs/Belong Together - Mark Ambor.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Belong Together.jpg" },
  { title: "Better Days", name: "Arman Cekin", source: "https://vi3e.pages.dev/Music/Songs/Better Days - Arman Cekin.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Better Days.jpg" },
  { title: "Better Days (2)", name: "NEIKED", source: "https://vi3e.pages.dev/Music/Songs/Better Days (2) - NEIKED.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Better Days (2).jpg" },
  { title: "Bittersweet Symphony", name: "GAMPER", source: "https://vi3e.pages.dev/Music/Songs/Bittersweet Symphony - GAMPER.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Bittersweet Symphony.jpg" },
  { title: "Born For This", name: "The Score", source: "https://vi3e.pages.dev/Music/Songs/Born For This - The Score.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Born For This.jpg" },
  { title: "Break My Heart", name: "Dua Lipa", source: "https://vi3e.pages.dev/Music/Songs/Break My Heart - Dua Lipa.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Break My Heart.jpg" },
  { title: "Breakdown", name: "Xaia", source: "https://vi3e.pages.dev/Music/Songs/Breakdown - Xaia.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Breakdown.jpg" },
  { title: "Call You Mine", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/Call You Mine - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Call You Mine.jpg" },
  { title: "Catching Fire", name: "Lvly", source: "https://vi3e.pages.dev/Music/Songs/Catching Fire - Lvly.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Catching Fire.jpg" },
  { title: "Chai and Sunshine", name: "Anjulie", source: "https://vi3e.pages.dev/Music/Songs/Chai and Sunshine - Anjulie.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Chai and Sunshine.jpg" },
  { title: "Cheap Thrills", name: "Sia", source: "https://vi3e.pages.dev/Music/Songs/Cheap Thrills - Sia.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Cheap Thrills.jpg" },
  { title: "Ciao Adios", name: "Anne-Marie", source: "https://vi3e.pages.dev/Music/Songs/Ciao Adios - Anne-Marie.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Ciao Adios.jpg" },
  { title: "Constellation", name: "Far Out", source: "https://vi3e.pages.dev/Music/Songs/Constellation - Far Out.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Constellation.jpg" },
  { title: "Cough", name: "Kizz Daniel", source: "https://vi3e.pages.dev/Music/Songs/Cough - Kizz Daniel.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Cough.jpg" },
  { title: "DARKSIDE", name: "Neoni", source: "https://vi3e.pages.dev/Music/Songs/DARKSIDE - Neoni.mp3", cover: "https://vi3e.pages.dev/Music/Covers/DARKSIDE.jpg" },
  { title: "Day or Night", name: "Jervis Campbell", source: "https://vi3e.pages.dev/Music/Songs/Day or Night - Jervis Campbell.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Day or Night.jpg" },
  { title: "death bed", name: "Powfu", source: "https://vi3e.pages.dev/Music/Songs/death bed  - Powfu.mp3", cover: "https://vi3e.pages.dev/Music/Covers/death bed.jpg" },
  { title: "Deep End", name: "Ameryh", source: "https://vi3e.pages.dev/Music/Songs/Deep End - Ameryh.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Deep End.jpg" },
  { title: "Dekhha Tenu", name: "Mohammad Faiz", source: "https://vi3e.pages.dev/Music/Songs/Dekhha Tenu - Mohammad Faiz.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Dekhha Tenu.jpg" },
  { title: "DÃ©jÃ  Vu", name: "Yves V", source: "https://vi3e.pages.dev/Music/Songs/DÃ©jÃ  Vu - Yves V.mp3", cover: "https://vi3e.pages.dev/Music/Covers/DÃ©jÃ  Vu.jpg" },
  { title: "Die For You", name: "VALORANT", source: "https://vi3e.pages.dev/Music/Songs/Die For You - VALORANT.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Die For You.jpg" },
  { title: "Die With A Smile", name: "Lady Gaga", source: "https://vi3e.pages.dev/Music/Songs/Die With A Smile - Lady Gaga.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Die With A Smile.jpg" },
  { title: "Dirty Thoughts", name: "Chloe Adams", source: "https://vi3e.pages.dev/Music/Songs/Dirty Thoughts - Chloe Adams.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Dirty Thoughts.jpg" },
  { title: "Distant Echoes", name: "VXLLAIN", source: "https://vi3e.pages.dev/Music/Songs/Distant Echoes - VXLLAIN.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Distant Echoes.jpg" },
  { title: "Dive", name: "Hot Shade, Mike Perry, Chris James", source: "https://vi3e.pages.dev/Music/Songs/Dive - Hot Shade, Mike Perry, Chris James.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Dive.jpg" },
  { title: "Don't Call Me Up", name: "Mabel", source: "https://vi3e.pages.dev/Music/Songs/Don't Call Me Up - Mabel.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Don't Call Me Up.jpg" },
  { title: "Don't Let Me Down", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/Don't Let Me Down - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Don't Let Me Down.jpg" },
  { title: "Drink And Shout", name: "Prezioso", source: "https://vi3e.pages.dev/Music/Songs/Drink And Shout - Prezioso.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Drink And Shout.jpg" },
  { title: "Dynasty", name: "MIIA", source: "https://vi3e.pages.dev/Music/Songs/Dynasty - MIIA.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Dynasty.jpg" },
  { title: "Eastside", name: "benny blanco", source: "https://vi3e.pages.dev/Music/Songs/Eastside - benny blanco.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Eastside.jpg" },
  { title: "echo", name: "Alexander Stewart", source: "https://vi3e.pages.dev/Music/Songs/echo - Alexander Stewart.mp3", cover: "https://vi3e.pages.dev/Music/Covers/echo.jpg" },
  { title: "Espresso", name: "Sabrina Carpenter", source: "https://vi3e.pages.dev/Music/Songs/Espresso - Sabrina Carpenter.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Espresso.jpg" },
  { title: "Every Second", name: "Mina Okabe", source: "https://vi3e.pages.dev/Music/Songs/Every Second - Mina Okabe.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Every Second.jpg" },
  { title: "Exposed", name: "APEK", source: "https://vi3e.pages.dev/Music/Songs/Exposed - APEK.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Exposed.jpg" },
  { title: "Eye to Eye", name: "Brett Miller, Veck", source: "https://vi3e.pages.dev/Music/Songs/Eye to Eye - Brett Miller, Veck.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Eye to Eye.jpg" },
  { title: "Fairytale", name: "Alexander Rybak", source: "https://vi3e.pages.dev/Music/Songs/Fairytale - Alexander Rybak.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Fairytale.jpg" },
  { title: "Fairytale", name: "Culture Code", source: "https://vi3e.pages.dev/Music/Songs/Fairytale (2) - Culture Code.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Fairytale (2).jpg" },
  { title: "Falling", name: "Trevor Daniel", source: "https://vi3e.pages.dev/Music/Songs/Falling - Trevor Daniel.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Falling.jpg" },
  { title: "Fast Lane", name: "Palm Trees", source: "https://vi3e.pages.dev/Music/Songs/Fast Lane - Palm Trees.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Fast Lane.jpg" },
  { title: "Fire!", name: "Alan Walker", source: "https://vi3e.pages.dev/Music/Songs/Fire! - Alan Walker.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Fire!.jpg" },
  { title: "Fish in the Sea", name: "Olivia Addams", source: "https://vi3e.pages.dev/Music/Songs/Fish in the Sea - Olivia Addams.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Fish in the Sea.jpg" },
  { title: "Flashbacks", name: "INNA", source: "https://vi3e.pages.dev/Music/Songs/Flashbacks - INNA.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Flashbacks.jpg" },
  { title: "Flicker Thicker Flames", name: "Lvly", source: "https://vi3e.pages.dev/Music/Songs/Flicker Thicker Flames - Lvly.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Flicker Thicker Flames.jpg" },
  { title: "Forever Young", name: "John De Sohn", source: "https://vi3e.pages.dev/Music/Songs/Forever Young - John De Sohn.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Forever Young.jpg" },
  { title: "FRIENDS", name: "Marshmello", source: "https://vi3e.pages.dev/Music/Songs/FRIENDS - Marshmello.mp3", cover: "https://vi3e.pages.dev/Music/Covers/FRIENDS.jpg" },
  { title: "Getaway", name: "Syn Cole", source: "https://vi3e.pages.dev/Music/Songs/Getaway - Syn Cole.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Getaway.jpg" },
  { title: "Hadal Ahbek", name: "Issam Alnajjar", source: "https://vi3e.pages.dev/Music/Songs/Hadal Ahbek - Issam Alnajjar.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Hadal Ahbek.jpg" },
  { title: "Half a Heart", name: "BEAUZ", source: "https://vi3e.pages.dev/Music/Songs/Half a Heart - BEAUZ.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Half a Heart.jpg" },
  { title: "Hall of Fame", name: "Nightcore Reality", source: "https://vi3e.pages.dev/Music/Songs/Hall of Fame - Nightcore Reality.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Hall of Fame.jpg" },
  { title: "Happy Now", name: "Kygo, Sandro Cavazza", source: "https://vi3e.pages.dev/Music/Songs/Happy Now - Kygo, Sandro Cavazza.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Happy Now.jpg" },
  { title: "Havana", name: "Camila Cabello", source: "https://vi3e.pages.dev/Music/Songs/Havana - Camila Cabello.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Havana.jpg" },
  { title: "Hayat ÅžaÅŸÄ±rtÄ±r", name: "Aydilge", source: "https://vi3e.pages.dev/Music/Songs/Hayat ÅžaÅŸÄ±rtÄ±r - Aydilge.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Hayat ÅžaÅŸÄ±rtÄ±r!.jpg" },
  { title: "Head Shoulders Knees & Toes", name: "Ofenbach", source: "https://vi3e.pages.dev/Music/Songs/Head Shoulders Knees & Toes - Ofenbach.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Head Shoulders Knees & Toes.jpg" },
  { title: "Heading Home", name: "Alan Walker", source: "https://vi3e.pages.dev/Music/Songs/Heading Home - Alan Walker.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Heading Home.jpg" },
  { title: "Heartbreak Anthem", name: "Galantis", source: "https://vi3e.pages.dev/Music/Songs/Heartbreak Anthem - Galantis.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Heartbreak Anthem.jpg" },
  { title: "Heat Waves", name: "Glass Animals", source: "https://vi3e.pages.dev/Music/Songs/Heat Waves - Glass Animals.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Heat Waves.jpg" },
  { title: "Heaven", name: "waykap", source: "https://vi3e.pages.dev/Music/Songs/Heaven - waykap.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Heaven.jpg" },
  { title: "Here With Me", name: "Marshmello", source: "https://vi3e.pages.dev/Music/Songs/Here With Me - Marshmello.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Here With Me.jpg" },
  { title: "Hollow", name: "My Buddy Mike", source: "https://vi3e.pages.dev/Music/Songs/Hollow - My Buddy Mike.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Hollow.jpg" },
  { title: "Hope", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/Hope - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Hope.jpg" },
  { title: "Hunts So Good", name: "Astrid S", source: "https://vi3e.pages.dev/Music/Songs/Hunts So Good - Astrid S.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Hunts So Good.jpg" },
  { title: "Hypnotized", name: "DEAMN", source: "https://vi3e.pages.dev/Music/Songs/Hypnotized - DEAMN.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Hypnotized.jpg" },
  { title: "I'll Be There", name: "Jess Glynne", source: "https://vi3e.pages.dev/Music/Songs/I'll Be There - Jess Glynne.mp3", cover: "https://vi3e.pages.dev/Music/Covers/I'll Be There.jpg" },
  { title: "I'll Wait For You", name: "Prince Woods", source: "https://vi3e.pages.dev/Music/Songs/I'll Wait For You - Prince Woods.mp3", cover: "https://vi3e.pages.dev/Music/Covers/I'll Wait For You.jpg" },
  { title: "I'm a Mess", name: "Bebe Rexha", source: "https://vi3e.pages.dev/Music/Songs/I'm a Mess - Bebe Rexha.mp3", cover: "https://vi3e.pages.dev/Music/Covers/I'm a Mess.jpg" },
  { title: "I Need More of You", name: "Hallman", source: "https://vi3e.pages.dev/Music/Songs/I Need More of You - Hallman.mp3", cover: "https://vi3e.pages.dev/Music/Covers/I Need More of You.jpg" },
  { title: "In the Name of Love", name: "Martin Garrix", source: "https://vi3e.pages.dev/Music/Songs/In the Name of Love - Martin Garrix.mp3", cover: "https://vi3e.pages.dev/Music/Covers/In the Name of Love.jpg" },
  { title: "Insane", name: "Black Gryph0n, Baasik", source: "https://vi3e.pages.dev/Music/Songs/Insane - Black Gryph0n, Baasik.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Insane.jpg" },
  { title: "Into Your Arms", name: "Witt Lowry", source: "https://vi3e.pages.dev/Music/Songs/Into Your Arms - Witt Lowry.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Into Your Arms.jpg" },
  { title: "It Ain't Me", name: "Kygo, Selena Gomez", source: "https://vi3e.pages.dev/Music/Songs/It Ain't Me - Kygo, Selena Gomez.mp3", cover: "https://vi3e.pages.dev/Music/Covers/It Ain't Me.jpg" },
  { title: "Ä°stersen", name: "Buray", source: "https://vi3e.pages.dev/Music/Songs/Ä°stersen - Buray.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Ä°stersen.jpg" },
  { title: "Just A Light", name: "Egzod", source: "https://vi3e.pages.dev/Music/Songs/Just A Light - Egzod.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Just A Light.jpg" },
  { title: "Just Keep Watching", name: "Tate McRae", source: "https://vi3e.pages.dev/Music/Songs/Just Keep Watching - Tate McRae.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Just Keep Watching.jpg" },
  { title: "Just My Type", name: "The Vamps", source: "https://vi3e.pages.dev/Music/Songs/Just My Type - The Vamps.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Just My Type.jpg" },
  { title: "Just Wanna Be Friends", name: "Basixx", source: "https://vi3e.pages.dev/Music/Songs/Just Wanna Be Friends - Basixx.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Just Wanna Be Friends.jpg" },
  { title: "la di die", name: "Nessa Barrett", source: "https://vi3e.pages.dev/Music/Songs/la di die - Nessa Barrett.mp3", cover: "https://vi3e.pages.dev/Music/Covers/la di die.jpg" },
  { title: "Let Me Go", name: "Hailee Steinfeld", source: "https://vi3e.pages.dev/Music/Songs/Let Me Go  - Hailee Steinfeld.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Let Me Go.jpg" },
  { title: "Lollipop", name: "CHROMANCE", source: "https://vi3e.pages.dev/Music/Songs/Lollipop - CHROMANCE.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Lollipop.jpg" },
  { title: "Lonely Together", name: "Avicii", source: "https://vi3e.pages.dev/Music/Songs/Lonely Together - Avicii.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Lonely Together.jpg" },
  { title: "Look Who's Cryin' Now", name: "Jessie Mupph", source: "https://vi3e.pages.dev/Music/Songs/Look Who's Cryin' Now - Jessie Murph.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Look Who's Cryin' Now.jpg" },
  { title: "Loote", name: "she's all yours", source: "https://vi3e.pages.dev/Music/Songs/she's all yours - Loote.mp3", cover: "https://vi3e.pages.dev/Music/Covers/she's all yours.jpg" },
  { title: "Love To Lose", name: "Sandro Cavazza", source: "https://vi3e.pages.dev/Music/Songs/Love To Lose - Sandro Cavazza.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Love To Lose.jpg" },
  { title: "lovely", name: "Billie Eilish", source: "https://vi3e.pages.dev/Music/Songs/lovely - Billie Eilish.mp3", cover: "https://vi3e.pages.dev/Music/Covers/lovely.jpg" },
  { title: "Loyal", name: "Young Bombs", source: "https://vi3e.pages.dev/Music/Songs/Loyal - Young Bombs.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Loyal.jpg" },
  { title: "Make Me Move - Tobu Remix", name: "Culture Code", source: "https://vi3e.pages.dev/Music/Songs/Make Me Move - Tobu Remix - Culture Code.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Make Me Move - Tobu Remix.jpg" },
  { title: "Mama", name: "Jonas Blue", source: "https://vi3e.pages.dev/Music/Songs/Mama - Jonas Blue.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Mama.jpg" },
  { title: "MAMIII", name: "Becky G", source: "https://vi3e.pages.dev/Music/Songs/MAMIII - Becky G.mp3", cover: "https://vi3e.pages.dev/Music/Covers/MAMIII.jpg" },
  { title: "Me & You", name: "Alex Skrindo", source: "https://vi3e.pages.dev/Music/Songs/Me & You - Alex Skrindo.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Me & You.jpg" },
  { title: "Me And My Broken Heart", name: "Rixton", source: "https://vi3e.pages.dev/Music/Songs/Me And My Broken Heart - Rixton.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Me And My Broken Heart.jpg" },
  { title: "Menak Wla Meni", name: "Hayit Murat", source: "https://vi3e.pages.dev/Music/Songs/Menak Wla Meni - Hayit Murat.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Menak Wla Meni.jpg" },
  { title: "Mind Games", name: "Sickick", source: "https://vi3e.pages.dev/Music/Songs/Mind Games - Sickick.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Mind Games.jpg" },
  { title: "MONEY ON THE DASH", name: "Elley DuhÃ©", source: "https://vi3e.pages.dev/Music/Songs/MONEY ON THE DASH - Elley DuhÃ©.mp3", cover: "https://vi3e.pages.dev/Music/Covers/MONEY ON THE DASH.jpg" },
  { title: "Move", name: "Adam Port", source: "https://vi3e.pages.dev/Music/Songs/Move - Adam Port.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Move.jpg" },
  { title: "My Way", name: "Chrxs Beats", source: "https://vi3e.pages.dev/Music/Songs/My Way - Chrxs Beats.mp3", cover: "https://vi3e.pages.dev/Music/Covers/My Way.jpg" },
  { title: "Nasty", name: "Sickick", source: "https://vi3e.pages.dev/Music/Songs/Nasty - Sickick.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Nasty.jpg" },
  { title: "New", name: "Daya", source: "https://vi3e.pages.dev/Music/Songs/New - Daya.mp3", cover: "https://vi3e.pages.dev/Music/Covers/New.jpg" },
  { title: "No Eyes On Me", name: "Justin Caruso", source: "https://vi3e.pages.dev/Music/Songs/No Eyes On Me - Justin Caruso.mp3", cover: "https://vi3e.pages.dev/Music/Covers/No Eyes On Me.jpg" },
  { title: "No Lie", name: "Sean Paul", source: "https://vi3e.pages.dev/Music/Songs/No Lie - Sean Paul.mp3", cover: "https://vi3e.pages.dev/Music/Covers/No Lie.jpg" },
  { title: "Ola La", name: "Kate Linn", source: "https://vi3e.pages.dev/Music/Songs/Ola La - Kate Linn.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Ola La.jpg" },
  { title: "On & On", name: "Cartoon", source: "https://vi3e.pages.dev/Music/Songs/On & On - Cartoon.mp3", cover: "https://vi3e.pages.dev/Music/Covers/On & On.jpg" },
  { title: "One More Time", name: "Luka Kloser", source: "https://vi3e.pages.dev/Music/Songs/One More Time - Luka Kloser.mp3", cover: "https://vi3e.pages.dev/Music/Covers/One More Time.jpg" },
  { title: "Other Side", name: "ILLENIUM", source: "https://vi3e.pages.dev/Music/Songs/Other Side - ILLENIUM.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Other Side.jpg" },
  { title: "Out Into Space", name: "Vicki Vox", source: "https://vi3e.pages.dev/Music/Songs/Out Into Space - Vicki Vox.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Out Into Space.jpg" },
  { title: "Overdrive", name: "Ofenbach", source: "https://vi3e.pages.dev/Music/Songs/Overdrive - Ofenbach.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Overdrive.jpg" },
  { title: "Paper Chasing", name: "Lvly", source: "https://vi3e.pages.dev/Music/Songs/Paper Chasing - Lvly.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Paper Chasing.jpg" },
  { title: "Paris", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/Paris - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Paris.jpg" },
  { title: "Party In The U.S.A.", name: "Miley Cyrus", source: "https://vi3e.pages.dev/Music/Songs/Party In The U.S.A. - Miley Cyrus.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Party In The U.S.A..jpg" },
  { title: "Payphone", name: "Maroon 5", source: "https://vi3e.pages.dev/Music/Songs/Payphone - Maroon 5.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Payphone.jpg" },
  { title: "PlouÄƒ", name: "Holy Molly", source: "https://vi3e.pages.dev/Music/Songs/PlouÄƒ - Holy Molly.mp3", cover: "https://vi3e.pages.dev/Music/Covers/PlouÄƒ.jpg" },
  { title: "Popular", name: "The Weeknd", source: "https://vi3e.pages.dev/Music/Songs/Popular - The Weeknd.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Popular.jpg" },
  { title: "Pretty Girl", name: "Maggie Lindemann", source: "https://vi3e.pages.dev/Music/Songs/Pretty Girl - Maggie Lindemann.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Pretty Girl.jpg" },
  { title: "Religion's Epitome", name: "Munn", source: "https://vi3e.pages.dev/Music/Songs/Religion_s Epitome - Munn.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Religion_s Epitome.jpg" },
  { title: "Rewrite The Stars", name: "James Arthur", source: "https://vi3e.pages.dev/Music/Songs/Rewrite The Stars - James Arthur.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Rewrite The Stars.jpg" },
  { title: "Rich Love", name: "OneRepublic", source: "https://vi3e.pages.dev/Music/Songs/Rich Love - OneRepublic.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Rich Love.jpg" },
  { title: "Ride or Die", name: "waykap", source: "https://vi3e.pages.dev/Music/Songs/Ride or Die - waykap.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Ride or Die.jpg" },
  { title: "Riding Shotgun", name: "Kygo", source: "https://vi3e.pages.dev/Music/Songs/Riding Shotgun - Kygo.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Riding Shotgun.jpg" },
  { title: "Rockabye", name: "Clean Bandit", source: "https://vi3e.pages.dev/Music/Songs/Rockabye- Clean Bandit.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Rockabye.jpg" },
  { title: "rockstar", name: "Post Malone, 21 Savage", source: "https://vi3e.pages.dev/Music/Songs/rockstar - Post Malone, 21 Savage.mp3", cover: "https://vi3e.pages.dev/Music/Covers/rockstar.jpg" },
  { title: "Runaway Kids", name: "dreamr", source: "https://vi3e.pages.dev/Music/Songs/Runaway Kids - dreamr.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Runaway Kids.jpg" },
  { title: "Running Out Of Roses", name: "Alan Walker", source: "https://vi3e.pages.dev/Music/Songs/Running Out Of Roses - Alan Walker.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Running Out Of Roses.jpg" },
  { title: "SAD!", name: "XXXTENTACION", source: "https://vi3e.pages.dev/Music/Songs/SAD! - XXXTENTACION.mp3", cover: "https://vi3e.pages.dev/Music/Covers/SAD!.jpg" },
  { title: "Safari", name: "Serena", source: "https://vi3e.pages.dev/Music/Songs/Safari - Serena.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Safari.jpg" },
  { title: "Sapphire", name: "Ed Sheeran", source: "https://vi3e.pages.dev/Music/Songs/Sapphire - Ed Sheeran.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Sapphire.jpg" },
  { title: "Savannah", name: "Diviners", source: "https://vi3e.pages.dev/Music/Songs/Savannah - Diviners.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Savannah.jpg" },
  { title: "Say You Won't Let Go", name: "James Arthur", source: "https://vi3e.pages.dev/Music/Songs/Say You Won't Let Go - James Arthur.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Say You Won't Let Go.jpg" },
  { title: "Self Control", name: "Laura Branigan", source: "https://vi3e.pages.dev/Music/Songs/Self Control - Laura Branigan.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Self Control.jpg" },
  { title: "September Trees", name: "memyself", source: "https://vi3e.pages.dev/Music/Songs/September Trees - memyself.mp3", cover: "https://vi3e.pages.dev/Music/Covers/September Trees.jpg" },
  { title: "SeÃ±orita", name: "Shawn Mendes, Camila Cabello", source: "https://vi3e.pages.dev/Music/Songs/SeÃ±orita - Shawn Mendes, Camila Cabello.mp3", cover: "https://vi3e.pages.dev/Music/Covers/SeÃ±orita.jpg" },
  { title: "Shameless", name: "Camila Cabello", source: "https://vi3e.pages.dev/Music/Songs/Shameless - Camila Cabello.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Shameless.jpg" },
  { title: "Shape of You", name: "Ed Sheeran", source: "https://vi3e.pages.dev/Music/Songs/Shape of You - Ed Sheeran.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Shape of You.jpg" },
  { title: "She Doesn't Mind", name: "TommyMuzzic", source: "https://vi3e.pages.dev/Music/Songs/She Doesn't Mind - TommyMuzzic.mp3", cover: "https://vi3e.pages.dev/Music/Covers/She Doesn't Mind.jpg" },
  { title: "Sink Or Swim", name: "OneRepublic", source: "https://vi3e.pages.dev/Music/Songs/Sink Or Swim - OneRepublic.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Sink Or Swim.jpg" },
  { title: "Sit Still, Look Pretty", name: "Daya", source: "https://vi3e.pages.dev/Music/Songs/Sit Still, Look Pretty - Daya.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Sit Still, Look Pretty.jpg" },
  { title: "Skinny Love", name: "Alex Grey", source: "https://vi3e.pages.dev/Music/Songs/Skinny Love - Alex Grey.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Skinny Love.jpg" },
  { title: "Someday", name: "OneRepublic", source: "https://vi3e.pages.dev/Music/Songs/Someday - OneRepublic.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Someday.jpg" },
  { title: "Someone to Rely On", name: "Gamma Skies", source: "https://vi3e.pages.dev/Music/Songs/Someone to Rely On - Gamma Skies.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Someone to Rely On.jpg" },
  { title: "Something Just Like This", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/Something Just Like This - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Something Just Like This.jpg" },
  { title: "Standing Still", name: "Joakim Molitor", source: "https://vi3e.pages.dev/Music/Songs/Standing Still - Joakim Molitor.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Standing Still.jpg" },
  { title: "Stars Will Align", name: "Kygo, Imagine Dragons", source: "https://vi3e.pages.dev/Music/Songs/Stars Will Align - Kygo, Imagine Dragons.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Stars Will Align.jpg" },
  { title: "Stargazing", name: "Kygo", source: "https://vi3e.pages.dev/Music/Songs/Stargazing - Kygo.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Stargazing.jpg" },
  { title: "Starving", name: "Hailee Steinfeld, Grey,  Zedd", source: "https://vi3e.pages.dev/Music/Songs/Starving - Hailee Steinfeld, Grey,  Zedd.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Starving.jpg" },
  { title: "Stay", name: "Gracie Abrams", source: "https://vi3e.pages.dev/Music/Songs/Stay - Gracie Abrams.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Stay.jpg" },
  { title: "Stereo Hearts", name: "Gym Class Heroes", source: "https://vi3e.pages.dev/Music/Songs/Stereo Hearts - Gym Class Heroes.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Stereo Hearts.jpg" },
  { title: "Stereo Love", name: "Edward Maya", source: "https://vi3e.pages.dev/Music/Songs/Stereo Love - Edward Maya.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Stereo Love.jpg" },
  { title: "Stitches", name: "Shawn Mendes", source: "https://vi3e.pages.dev/Music/Songs/Stitches - Shawn Mendes.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Stitches.jpg" },
  { title: "Stranger Things", name: "Kygo", source: "https://vi3e.pages.dev/Music/Songs/Stranger Things - Kygo.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Stranger Things.jpg" },
  { title: "Sugar", name: "Maroon 5", source: "https://vi3e.pages.dev/Music/Songs/Sugar - Maroon 5.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Sugar.jpg" },
  { title: "Summer Bath", name: "Wahidul Choudhury", source: "https://vi3e.pages.dev/Music/Songs/Summer Bath - Wahidul Choudhury.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Summer Bath.jpg" },
  { title: "Sunroof", name: "Nicky Youre", source: "https://vi3e.pages.dev/Music/Songs/Sunroof - Nicky Youre.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Sunroof.jpg" },
  { title: "Superhero In My Sleep", name: "Rival", source: "https://vi3e.pages.dev/Music/Songs/Superhero In My Sleep - Rival.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Superhero In My Sleep.jpg" },
  { title: "Sweet but Psycho", name: "Ava Max", source: "https://vi3e.pages.dev/Music/Songs/Sweet but Psycho - Ava Max.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Sweet but Psycho.jpg" },
  { title: "Symphony", name: "Clean Bandit", source: "https://vi3e.pages.dev/Music/Songs/Symphony - Clean Bandit.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Symphony.jpg" },
  { title: "Tarantella", name: "Gabry Ponte", source: "https://vi3e.pages.dev/Music/Songs/Tarantella - Gabry Ponte.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Tarantella.jpg" },
  { title: "Tattoo", name: "Loreen", source: "https://vi3e.pages.dev/Music/Songs/Tattoo - Loreen.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Tattoo.jpg" },
  { title: "Telepatia", name: "Farizki", source: "https://vi3e.pages.dev/Music/Songs/Telepatia - Farizki.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Telepatia.jpg" },
  { title: "Tell Me Why", name: "Loote", source: "https://vi3e.pages.dev/Music/Songs/Tell Me Why - Loote.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Tell Me Why.jpg" },
  { title: "Tell Me Why", name: "Locte", source: "https://vi3e.pages.dev/Music/Songs/Tell Me Why - Locte.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Tell Me Why.jpg" },
  { title: "That's So True", name: "Gracie Abrams", source: "https://vi3e.pages.dev/Music/Songs/That's So True - Gracie Abrams.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Thatâ€™s So True.jpg" },
  { title: "The Greatest", name: "Sia", source: "https://vi3e.pages.dev/Music/Songs/The Greatest - Sia.mp3", cover: "https://vi3e.pages.dev/Music/Covers/The Greatest.jpg" },
  { title: "The Great Escape", name: "Josie Edwards", source: "https://vi3e.pages.dev/Music/Songs/The Great Escape - Josie Edwards.mp3", cover: "https://vi3e.pages.dev/Music/Covers/The Great Escape.jpg" },
  { title: "The Middle", name: "Zedd", source: "https://vi3e.pages.dev/Music/Songs/The Middle - Zedd.mp3", cover: "https://vi3e.pages.dev/Music/Covers/The Middle.jpg" },
  { title: "Things I Love", name: "Lvly", source: "https://vi3e.pages.dev/Music/Songs/Things I Love - Lvly.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Things I Love.jpg" },
  { title: "this is what heartbreak feels like", name: "JVKE", source: "https://vi3e.pages.dev/Music/Songs/this is what heartbreak feels like - JVKE.mp3", cover: "https://vi3e.pages.dev/Music/Covers/this is what heartbreak feels like.jpg" },
  { title: "Thumbs", name: "Sabrina Carpenter", source: "https://vi3e.pages.dev/Music/Songs/Thumbs - Sabrina Carpenter.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Thumbs.jpg" },
  { title: "Thunder", name: "Gabry Ponte", source: "https://vi3e.pages.dev/Music/Songs/Thunder - Gabry Ponte.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Thunder.jpg" },
  { title: "Tick Tock", name: "Clean Bandit", source: "https://vi3e.pages.dev/Music/Songs/Tick Tock - Clean Bandit.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Tick Tock.jpg" },
  { title: "TiK ToK", name: "EQRIC", source: "https://vi3e.pages.dev/Music/Songs/TiK ToK - EQRIC.mp3", cover: "https://vi3e.pages.dev/Music/Covers/TiK ToK.jpg" },
  { title: "Too Late", name: "OmgLoSteve", source: "https://vi3e.pages.dev/Music/Songs/Too Late - OmgLoSteve.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Too Late.jpg" },
  { title: "Tutsak", name: "Sefo", source: "https://vi3e.pages.dev/Music/Songs/Tutsak - Sefo.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Tutsak.jpg" },
  { title: "Up", name: "INNA", source: "https://vi3e.pages.dev/Music/Songs/UP - INNA.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Up.jpg" },
  { title: "Used To", name: "Sandro Cavazza", source: "https://vi3e.pages.dev/Music/Songs/Used To - Sandro Cavazza.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Used To.jpg" },
  { title: "Wake Me Up In Paris", name: "Anthony Keyrouz", source: "https://vi3e.pages.dev/Music/Songs/Wake Me Up In Paris - Anthony Keyrouz.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Wake Me Up In Paris.jpg" },
  { title: "Waiting", name: "Vicetone", source: "https://vi3e.pages.dev/Music/Songs/Waiting - Vicetone.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Waiting.jpg" },
  { title: "Walk Thru Fire", name: "Vicetone", source: "https://vi3e.pages.dev/Music/Songs/Walk Thru Fire - Vicetone.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Walk Thru Fire.jpg" },
  { title: "Way Back Home", name: "Sam Feldt", source: "https://vi3e.pages.dev/Music/Songs/Way Back Home - Sam Feldt.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Way Back Home.jpg" },
  { title: "we can't be friends", name: "Ariana Grande", source: "https://vi3e.pages.dev/Music/Songs/we can't be friends - Ariana Grande.mp3", cover: "https://vi3e.pages.dev/Music/Covers/we can't be friends.jpg" },
  { title: "We Don't Talk Anymore", name: "Charlie Puth", source: "https://vi3e.pages.dev/Music/Songs/We Don't Talk Anymore - Charlie Puth.mp3", cover: "https://vi3e.pages.dev/Music/Covers/We Don't Talk Anymore.jpg" },
  { title: "We Go Down Together", name: "BLAEKER", source: "https://vi3e.pages.dev/Music/Songs/We Go Down Together - BLAEKER.mp3", cover: "https://vi3e.pages.dev/Music/Covers/We Go Down Together.jpg" },
  { title: "We Should Be Sorry", name: "Axel Johansson", source: "https://vi3e.pages.dev/Music/Songs/We Should Be Sorry - Axel Johansson.mp3", cover: "https://vi3e.pages.dev/Music/Covers/We Should Be Sorry.jpg" },
  { title: "What If", name: "Johnny Orlando", source: "https://vi3e.pages.dev/Music/Songs/What If - Johnny Orlando.mp3", cover: "https://vi3e.pages.dev/Music/Covers/What If.jpg" },
  { title: "Whatever", name: "Kygo, Ava Max", source: "https://vi3e.pages.dev/Music/Songs/Whatever - Kygo, Ava Max.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Whatever.jpg" },
  { title: "When You're Lonely", name: "Hoang", source: "https://vi3e.pages.dev/Music/Songs/When You_re Lonely - Hoang.mp3", cover: "https://vi3e.pages.dev/Music/Covers/When You're Lonely.jpg" },
  { title: "Where Are You Now", name: "Lost Frequencies", source: "https://vi3e.pages.dev/Music/Songs/Where Are You Now - Lost Frequencies.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Where Are You Now.jpg" },
  { title: "Wilder", name: "Gamma Skies", source: "https://vi3e.pages.dev/Music/Songs/Wilder - Gamma Skies.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Wilder.jpg" },
  { title: "Without Me", name: "Halsey", source: "https://vi3e.pages.dev/Music/Songs/Without Me - Halsey.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Without Me.jpg" },
  { title: "Wrap Me In Plastic", name: "CHROMANCE", source: "https://vi3e.pages.dev/Music/Songs/Wrap Me In Plastic - CHROMANCE.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Wrap Me In Plastic.jpg" },
  { title: "You should be sad", name: "Halsey", source: "https://vi3e.pages.dev/Music/Songs/You should be sad - Halsey.mp3", cover: "https://vi3e.pages.dev/Music/Covers/You should be sad.jpg" },
  { title: "Young", name: "The Chainsmokers", source: "https://vi3e.pages.dev/Music/Songs/Young - The Chainsmokers.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Young.jpg" },
  { title: "Ð”Ð¸ÐºÐ°Ñ Ð»ÑŒÐ²Ð¸Ñ†Ð°", name: "ALEX", source: "https://vi3e.pages.dev/Music/Songs/Ð”Ð¸ÐºÐ°Ñ Ð»ÑŒÐ²Ð¸Ñ†Ð° - ALEX.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Ð”Ð¸ÐºÐ°Ñ Ð»ÑŒÐ²Ð¸Ñ†Ð°.jpg" },
  { title: "Ð‡Ð´Ðµ Ð´Ð°Ñ…", name: "Klavdia Petrivna", source: "https://vi3e.pages.dev/Music/Songs/Ð‡Ð´Ðµ Ð´Ð°Ñ… - Klavdia Petrivna.mp3", cover: "https://vi3e.pages.dev/Music/Covers/Ð‡Ð´Ðµ Ð´Ð°Ñ….jpg" }
];