export const songs = [
  { title: "1 last bye", name: "Kiran", source: "./Songs/1 last bye - Kiran.mp3", cover: "./Covers/1 last bye.jpg" },
  { title: "2 Hearts", name: "Sam Feldt", source: "./Songs/2 Hearts - Sam Feldt.mp3", cover: "./Covers/2 Hearts.jpg" },
  { title: "8 Letters", name: "Why Don't We", source: "./Songs/8 Letters - Why Don't We.mp3", cover: "./Covers/8 Letters.jpg" },
  { title: "10:35", name: "Tiësto", source: "./Songs/10_35 - Tiësto.mp3", cover: "./Covers/10_35.jpg" },
  { title: "2002", name: "Anne-Marie", source: "./Songs/2002 - Anne-Marie.mp3", cover: "./Covers/2002.jpg" },
  { title: "A Different Way", name: "DJ Snake", source: "./Songs/A Different Way- DJ Snake.mp3", cover: "./Covers/A Different Way.jpg" },
  { title: "A Thousand Years", name: "James Arthur", source: "./Songs/A Thousand Years - James Arthur.mp3", cover: "./Covers/A Thousand Years.jpg" },
  { title: "All About It", name: "Deep Chills", source: "./Songs/All About It - Deep Chills.mp3", cover: "./Covers/All About It.jpg" },
  { title: "All Falls Down", name: "Alan Walker", source: "./Songs/All Falls Down - Alan Walker.mp3", cover: "./Covers/All Falls Down.jpg" },
  { title: "All We Are", name: "Richello", source: "./Songs/All We Are - Richello.mp3", cover: "./Covers/All We Are.jpg" },
  { title: "All We Know", name: "The Chainsmokers", source: "./Songs/All We Know - The Chainsmokers.mp3", cover: "./Covers/All We Know.jpg" },
  { title: "Another Love", name: "Tom Odell", source: "./Songs/Another Love - Tom Odell.mp3", cover: "./Covers/Another Love.jpg" },
  { title: "Bad Girl", name: "Daya", source: "./Songs/Bad Girl - Daya.mp3", cover: "./Covers/Bad Girl.jpg" },
  { title: "Beach House", name: "The Chainsmokers", source: "./Songs/Beach House - The Chainsmokers.mp3", cover: "./Covers/Beach House.jpg" },
  { title: "Beautiful Mistakes", name: "Maroon 5", source: "./Songs/Beautiful Mistakes - Maroon 5.mp3", cover: "./Covers/Beautiful Mistakes.jpg" },
  { title: "Beautiful Now", name: "Zedd", source: "./Songs/Beautiful Now - Zedd.mp3", cover: "./Covers/Beautiful Now.jpg" },
  { title: "Believers", name: "Alan Walker", source: "./Songs/Believers - Alan Walker.mp3", cover: "./Covers/Believers.jpg" },
  { title: "Belong Together", name: "Mark Ambor", source: "./Songs/Belong Together - Mark Ambor.mp3", cover: "./Covers/Belong Together.jpg" },
  { title: "Better Days", name: "Arman Cekin", source: "./Songs/Better Days - Arman Cekin.mp3", cover: "./Covers/Better Days.jpg" },
  { title: "Better Days (2)", name: "NEIKED", source: "./Songs/Better Days (2) - NEIKED.mp3", cover: "./Covers/Better Days (2).jpg" },
  { title: "Bittersweet Symphony", name: "GAMPER", source: "./Songs/Bittersweet Symphony - GAMPER.mp3", cover: "./Covers/Bittersweet Symphony.jpg" },
  { title: "Born For This", name: "The Score", source: "./Songs/Born For This - The Score.mp3", cover: "./Covers/Born For This.jpg" },
  { title: "Break My Heart", name: "Dua Lipa", source: "./Songs/Break My Heart - Dua Lipa.mp3", cover: "./Covers/Break My Heart.jpg" },
  { title: "Breakdown", name: "Xaia", source: "./Songs/Breakdown - Xaia.mp3", cover: "./Covers/Breakdown.jpg" },
  { title: "Call You Mine", name: "The Chainsmokers", source: "./Songs/Call You Mine - The Chainsmokers.mp3", cover: "./Covers/Call You Mine.jpg" },
  { title: "Catching Fire", name: "Lvly", source: "./Songs/Catching Fire - Lvly.mp3", cover: "./Covers/Catching Fire.jpg" },
  { title: "Chai and Sunshine", name: "Anjulie", source: "./Songs/Chai and Sunshine - Anjulie.mp3", cover: "./Covers/Chai and Sunshine.jpg" },
  { title: "Cheap Thrills", name: "Sia", source: "./Songs/Cheap Thrills - Sia.mp3", cover: "./Covers/Cheap Thrills.jpg" },
  { title: "Colors", name: "Jason Derulo", source: "./Songs/Colors - Jason Derulo.mp3", cover: "./Covers/Colors.jpg" },
  { title: "Constellation", name: "Far Out", source: "./Songs/Constellation - Far Out.mp3", cover: "./Covers/Constellation.jpg" },
  { title: "Cough", name: "Kizz Daniel", source: "./Songs/Cough - Kizz Daniel.mp3", cover: "./Covers/Cough.jpg" },
  { title: "DARKSIDE", name: "Neoni", source: "./Songs/DARKSIDE - Neoni.mp3", cover: "./Covers/DARKSIDE.jpg" },
  { title: "Day or Night", name: "Jervis Campbell", source: "./Songs/Day or Night - Jervis Campbell.mp3", cover: "./Covers/Day or Night.jpg" },
  { title: "death bed", name: "Powfu", source: "./Songs/death bed  - Powfu.mp3", cover: "./Covers/death bed.jpg" },
  { title: "Deep End", name: "Ameryh", source: "./Songs/Deep End - Ameryh.mp3", cover: "./Covers/Deep End.jpg" },
  { title: "Dekhha Tenu", name: "Mohammad Faiz", source: "./Songs/Dekhha Tenu - Mohammad Faiz.mp3", cover: "./Covers/Dekhha Tenu.jpg" },
  { title: "Deja  Vu", name: "Yves V", source: "./Songs/Dejavu - Yves V.mp3", cover: "./Covers/Dejavu.jpg" },
  { title: "Die For You", name: "VALORANT", source: "./Songs/Die For You - VALORANT.mp3", cover: "./Covers/Die For You.jpg" },
  { title: "Die With A Smile", name: "Lady Gaga", source: "./Songs/Die With A Smile - Lady Gaga.mp3", cover: "./Covers/Die With A Smile.jpg" },
  { title: "Dirty Thoughts", name: "Chloe Adams", source: "./Songs/Dirty Thoughts - Chloe Adams.mp3", cover: "./Covers/Dirty Thoughts.jpg" },
  { title: "Distant Echoes", name: "VXLLAIN", source: "./Songs/Distant Echoes - VXLLAIN.mp3", cover: "./Covers/Distant Echoes.jpg" },
  { title: "Dive", name: "Hot Shade, Mike Perry, Chris James", source: "./Songs/Dive - Hot Shade, Mike Perry, Chris James.mp3", cover: "./Covers/Dive.jpg" },
  { title: "Don't Call Me Up", name: "Mabel", source: "./Songs/Don't Call Me Up - Mabel.mp3", cover: "./Covers/Don't Call Me Up.jpg" },
  { title: "Don't Let Me Down", name: "The Chainsmokers", source: "./Songs/Don't Let Me Down - The Chainsmokers.mp3", cover: "./Covers/Don't Let Me Down.jpg" },
  { title: "Drink And Shout", name: "Prezioso", source: "./Songs/Drink And Shout - Prezioso.mp3", cover: "./Covers/Drink And Shout.jpg" },
  { title: "Dynasty", name: "MIIA", source: "./Songs/Dynasty - MIIA.mp3", cover: "./Covers/Dynasty.jpg" },
  { title: "Eastside", name: "benny blanco", source: "./Songs/Eastside - benny blanco.mp3", cover: "./Covers/Eastside.jpg" },
  { title: "echo", name: "Alexander Stewart", source: "./Songs/echo - Alexander Stewart.mp3", cover: "./Covers/echo.jpg" },
  { title: "Espresso", name: "Sabrina Carpenter", source: "./Songs/Espresso - Sabrina Carpenter.mp3", cover: "./Covers/Espresso.jpg" },
  { title: "Every Second", name: "Mina Okabe", source: "./Songs/Every Second - Mina Okabe.mp3", cover: "./Covers/Every Second.jpg" },
  { title: "Exposed", name: "APEK", source: "./Songs/Exposed - APEK.mp3", cover: "./Covers/Exposed.jpg" },
  { title: "Eye to Eye", name: "Brett Miller, Veck", source: "./Songs/Eye to Eye - Brett Miller, Veck.mp3", cover: "./Covers/Eye to Eye.jpg" },
  { title: "Fairytale", name: "Alexander Rybak", source: "./Songs/Fairytale - Alexander Rybak.mp3", cover: "./Covers/Fairytale.jpg" },
  { title: "Fairytale", name: "Culture Code", source: "./Songs/Fairytale (2) - Culture Code.mp3", cover: "./Covers/Fairytale (2).jpg" },
  { title: "Falling", name: "Trevor Daniel", source: "./Songs/Falling - Trevor Daniel.mp3", cover: "./Covers/Falling.jpg" },
  { title: "Fast Lane", name: "Palm Trees", source: "./Songs/Fast Lane - Palm Trees.mp3", cover: "./Covers/Fast Lane.jpg" },
  { title: "Fire!", name: "Alan Walker", source: "./Songs/Fire! - Alan Walker.mp3", cover: "./Covers/Fire!.jpg" },
  { title: "Fireflies", name: "Owl City", source: "./Songs/Fireflies - Owl City.mp3", cover: "./Covers/Fireflies.jpg" },
  { title: "Fish in the Sea", name: "Olivia Addams", source: "./Songs/Fish in the Sea - Olivia Addams.mp3", cover: "./Covers/Fish in the Sea.jpg" },
  { title: "Flashbacks", name: "INNA", source: "./Songs/Flashbacks - INNA.mp3", cover: "./Covers/Flashbacks.jpg" },
  { title: "Flicker Thicker Flames", name: "Lvly", source: "./Songs/Flicker Thicker Flames - Lvly.mp3", cover: "./Covers/Flicker Thicker Flames.jpg" },
  { title: "Forever Young", name: "John De Sohn", source: "./Songs/Forever Young - John De Sohn.mp3", cover: "./Covers/Forever Young.jpg" },
  { title: "FRIENDS", name: "Marshmello", source: "./Songs/FRIENDS - Marshmello.mp3", cover: "./Covers/FRIENDS.jpg" },
  { title: "Getaway", name: "Syn Cole", source: "./Songs/Getaway - Syn Cole.mp3", cover: "./Covers/Getaway.jpg" },
  { title: "Hadal Ahbek", name: "Issam Alnajjar", source: "./Songs/Hadal Ahbek - Issam Alnajjar.mp3", cover: "./Covers/Hadal Ahbek.jpg" },
  { title: "Half a Heart", name: "BEAUZ", source: "./Songs/Half a Heart - BEAUZ.mp3", cover: "./Covers/Half a Heart.jpg" },
  { title: "Hall of Fame", name: "Nightcore Reality", source: "./Songs/Hall of Fame - Nightcore Reality.mp3", cover: "./Covers/Hall of Fame.jpg" },
  { title: "Happy Now", name: "Kygo, Sandro Cavazza", source: "./Songs/Happy Now - Kygo, Sandro Cavazza.mp3", cover: "./Covers/Happy Now.jpg" },
  { title: "Havana", name: "Camila Cabello", source: "./Songs/Havana - Camila Cabello.mp3", cover: "./Covers/Havana.jpg" },
  { title: "Hayat Şaşırtır", name: "Aydilge", source: "./Songs/Hayat Şaşırtır - Aydilge.mp3", cover: "./Covers/Hayat Şaşırtır!.jpg" },
  { title: "Head Shoulders Knees & Toes", name: "Ofenbach", source: "./Songs/Head Shoulders Knees & Toes - Ofenbach.mp3", cover: "./Covers/Head Shoulders Knees & Toes.jpg" },
  { title: "Heading Home", name: "Alan Walker", source: "./Songs/Heading Home - Alan Walker.mp3", cover: "./Covers/Heading Home.jpg" },
  { title: "Heartbreak Anthem", name: "Galantis", source: "./Songs/Heartbreak Anthem - Galantis.mp3", cover: "./Covers/Heartbreak Anthem.jpg" },
  { title: "Heat Waves", name: "Glass Animals", source: "./Songs/Heat Waves - Glass Animals.mp3", cover: "./Covers/Heat Waves.jpg" },
  { title: "Heaven", name: "waykap", source: "./Songs/Heaven - waykap.mp3", cover: "./Covers/Heaven.jpg" },
  { title: "Here With Me", name: "Marshmello", source: "./Songs/Here With Me - Marshmello.mp3", cover: "./Covers/Here With Me.jpg" },
  { title: "Hollow", name: "My Buddy Mike", source: "./Songs/Hollow - My Buddy Mike.mp3", cover: "./Covers/Hollow.jpg" },
  { title: "Hope", name: "The Chainsmokers", source: "./Songs/Hope - The Chainsmokers.mp3", cover: "./Covers/Hope.jpg" },
  { title: "Hurts So Good", name: "Astrid S", source: "./Songs/Hurts So Good - Astrid S.mp3", cover: "./Covers/Hurts So Good.jpg" },
  { title: "Hypnotized", name: "DEAMN", source: "./Songs/Hypnotized - DEAMN.mp3", cover: "./Covers/Hypnotized.jpg" },
  { title: "I'll Be There", name: "Jess Glynne", source: "./Songs/I'll Be There - Jess Glynne.mp3", cover: "./Covers/I'll Be There.jpg" },
  { title: "I'll Wait For You", name: "Prince Woods", source: "./Songs/I'll Wait For You - Prince Woods.mp3", cover: "./Covers/I'll Wait For You.jpg" },
  { title: "I'm a Mess", name: "Bebe Rexha", source: "./Songs/I'm a Mess - Bebe Rexha.mp3", cover: "./Covers/I'm a Mess.jpg" },
  { title: "I Need More of You", name: "Hallman", source: "./Songs/I Need More of You - Hallman.mp3", cover: "./Covers/I Need More of You.jpg" },
  { title: "In the Name of Love", name: "Martin Garrix", source: "./Songs/In the Name of Love - Martin Garrix.mp3", cover: "./Covers/In the Name of Love.jpg" },
  { title: "Insane", name: "Black Gryph0n, Baasik", source: "./Songs/Insane - Black Gryph0n, Baasik.mp3", cover: "./Covers/Insane.jpg" },
  { title: "Into Your Arms", name: "Witt Lowry", source: "./Songs/Into Your Arms - Witt Lowry.mp3", cover: "./Covers/Into Your Arms.jpg" },
  { title: "It Ain't Me", name: "Kygo, Selena Gomez", source: "./Songs/It Ain't Me - Kygo, Selena Gomez.mp3", cover: "./Covers/It Ain't Me.jpg" },
  { title: "İstersen", name: "Buray", source: "./Songs/İstersen - Buray.mp3", cover: "./Covers/İstersen.jpg" },
  { title: "Just A Light", name: "Egzod", source: "./Songs/Just A Light - Egzod.mp3", cover: "./Covers/Just A Light.jpg" },
  { title: "Just Keep Watching", name: "Tate McRae", source: "./Songs/Just Keep Watching - Tate McRae.mp3", cover: "./Covers/Just Keep Watching.jpg" },
  { title: "Just My Type", name: "The Vamps", source: "./Songs/Just My Type - The Vamps.mp3", cover: "./Covers/Just My Type.jpg" },
  { title: "Just Wanna Be Friends", name: "Basixx", source: "./Songs/Just Wanna Be Friends - Basixx.mp3", cover: "./Covers/Just Wanna Be Friends.jpg" },
  { title: "la di die", name: "Nessa Barrett", source: "./Songs/la di die - Nessa Barrett.mp3", cover: "./Covers/la di die.jpg" },
  { title: "Let Me Go", name: "Hailee Steinfeld", source: "./Songs/Let Me Go  - Hailee Steinfeld.mp3", cover: "./Covers/Let Me Go.jpg" },
  { title: "Lollipop", name: "CHROMANCE", source: "./Songs/Lollipop - CHROMANCE.mp3", cover: "./Covers/Lollipop.jpg" },
  { title: "Lonely Together", name: "Avicii", source: "./Songs/Lonely Together - Avicii.mp3", cover: "./Covers/Lonely Together.jpg" },
  { title: "Look Who's Cryin' Now", name: "Jessie Murph", source: "./Songs/Look Who's Cryin' Now - Jessie Murph.mp3", cover: "./Covers/Look Who's Cryin' Now.jpg" },
  { title: "Loote", name: "she's all yours", source: "./Songs/she's all yours - Loote.mp3", cover: "./Covers/she's all yours.jpg" },
  { title: "Love To Lose", name: "Sandro Cavazza", source: "./Songs/Love To Lose - Sandro Cavazza.mp3", cover: "./Covers/Love To Lose.jpg" },
  { title: "lovely", name: "Billie Eilish", source: "./Songs/lovely - Billie Eilish.mp3", cover: "./Covers/lovely.jpg" },
  { title: "Loyal", name: "Young Bombs", source: "./Songs/Loyal - Young Bombs.mp3", cover: "./Covers/Loyal.jpg" },
  { title: "Make Me Move - Tobu Remix", name: "Culture Code", source: "./Songs/Make Me Move - Tobu Remix - Culture Code.mp3", cover: "./Covers/Make Me Move - Tobu Remix.jpg" },
  { title: "Mama", name: "Jonas Blue", source: "./Songs/Mama - Jonas Blue.mp3", cover: "./Covers/Mama.jpg" },
  { title: "MAMIII", name: "Becky G", source: "./Songs/MAMIII - Becky G.mp3", cover: "./Covers/MAMIII.jpg" },
  { title: "Me & You", name: "Alex Skrindo", source: "./Songs/Me & You - Alex Skrindo.mp3", cover: "./Covers/Me & You.jpg" },
  { title: "Me And My Broken Heart", name: "Rixton", source: "./Songs/Me And My Broken Heart - Rixton.mp3", cover: "./Covers/Me And My Broken Heart.jpg" },
  { title: "Menak Wla Meni", name: "Hayit Murat", source: "./Songs/Menak Wla Meni - Hayit Murat.mp3", cover: "./Covers/Menak Wla Meni.jpg" },
  { title: "Mind Games", name: "Sickick", source: "./Songs/Mind Games - Sickick.mp3", cover: "./Covers/Mind Games.jpg" },
  { title: "MONEY ON THE DASH", name: "Elley Duhé", source: "./Songs/MONEY ON THE DASH - Elley Duhé.mp3", cover: "./Covers/MONEY ON THE DASH.jpg" },
  { title: "Move", name: "Adam Port", source: "./Songs/Move - Adam Port.mp3", cover: "./Covers/Move.jpg" },
  { title: "My Way", name: "Chrxs Beats", source: "./Songs/My Way - Chrxs Beats.mp3", cover: "./Covers/My Way.jpg" },
  { title: "Nasty", name: "Sickick", source: "./Songs/Nasty - Sickick.mp3", cover: "./Covers/Nasty.jpg" },
  { title: "New", name: "Daya", source: "./Songs/New - Daya.mp3", cover: "./Covers/New.jpg" },
  { title: "No Eyes On Me", name: "Justin Caruso", source: "./Songs/No Eyes On Me - Justin Caruso.mp3", cover: "./Covers/No Eyes On Me.jpg" },
  { title: "No Lie", name: "Sean Paul", source: "./Songs/No Lie - Sean Paul.mp3", cover: "./Covers/No Lie.jpg" },
  { title: "Ola La", name: "Kate Linn", source: "./Songs/Ola La - Kate Linn.mp3", cover: "./Covers/Ola La.jpg" },
  { title: "On & On", name: "Cartoon", source: "./Songs/On & On - Cartoon.mp3", cover: "./Covers/On & On.jpg" },
  { title: "One More Time", name: "Luka Kloser", source: "./Songs/One More Time - Luka Kloser.mp3", cover: "./Covers/One More Time.jpg" },
  { title: "Other Side", name: "ILLENIUM", source: "./Songs/Other Side - ILLENIUM.mp3", cover: "./Covers/Other Side.jpg" },
  { title: "Out Into Space", name: "Vicki Vox", source: "./Songs/Out Into Space - Vicki Vox.mp3", cover: "./Covers/Out Into Space.jpg" },
  { title: "Overdrive", name: "Ofenbach", source: "./Songs/Overdrive - Ofenbach.mp3", cover: "./Covers/Overdrive.jpg" },
  { title: "Paper Chasing", name: "Lvly", source: "./Songs/Paper Chasing - Lvly.mp3", cover: "./Covers/Paper Chasing.jpg" },
  { title: "Paris", name: "The Chainsmokers", source: "./Songs/Paris - The Chainsmokers.mp3", cover: "./Covers/Paris.jpg" },
  { title: "Party In The U.S.A.", name: "Miley Cyrus", source: "./Songs/Party In The U.S.A. - Miley Cyrus.mp3", cover: "./Covers/Party In The U.S.A..jpg" },
  { title: "Payphone", name: "Maroon 5", source: "./Songs/Payphone - Maroon 5.mp3", cover: "./Covers/Payphone.jpg" },
  { title: "Plouă", name: "Holy Molly", source: "./Songs/Plouă - Holy Molly.mp3", cover: "./Covers/Plouă.jpg" },
  { title: "Popular", name: "The Weeknd", source: "./Songs/Popular - The Weeknd.mp3", cover: "./Covers/Popular.jpg" },
  { title: "Pretty Girl", name: "Maggie Lindemann", source: "./Songs/Pretty Girl - Maggie Lindemann.mp3", cover: "./Covers/Pretty Girl.jpg" },
  { title: "Religion's Epitome", name: "Munn", source: "./Songs/Religion_s Epitome - Munn.mp3", cover: "./Covers/Religion_s Epitome.jpg" },
  { title: "Rewrite The Stars", name: "James Arthur", source: "./Songs/Rewrite The Stars - James Arthur.mp3", cover: "./Covers/Rewrite The Stars.jpg" },
  { title: "Rich Love", name: "OneRepublic", source: "./Songs/Rich Love - OneRepublic.mp3", cover: "./Covers/Rich Love.jpg" },
  { title: "Ride or Die", name: "waykap", source: "./Songs/Ride or Die - waykap.mp3", cover: "./Covers/Ride or Die.jpg" },
  { title: "Riding Shotgun", name: "Kygo", source: "./Songs/Riding Shotgun - Kygo.mp3", cover: "./Covers/Riding Shotgun.jpg" },
  { title: "Rise", name: "Jonas Blue", source: "./Songs/Rise - Jonas Blue.mp3", cover: "./Covers/Rise.jpg" },
  { title: "Rockabye", name: "Clean Bandit", source: "./Songs/Rockabye- Clean Bandit.mp3", cover: "./Covers/Rockabye.jpg" },
  { title: "Ruin Me", name: "Elevator Boys", source: "./Songs/Ruin Me - Elevator Boys.mp3", cover: "./Covers/Ruin Me.jpg" },
  { title: "Runaway Kids", name: "dreamr", source: "./Songs/Runaway Kids - dreamr.mp3", cover: "./Covers/Runaway Kids.jpg" },
  { title: "Running Out Of Roses", name: "Alan Walker", source: "./Songs/Running Out Of Roses - Alan Walker.mp3", cover: "./Covers/Running Out Of Roses.jpg" },
  { title: "SAD!", name: "XXXTENTACION", source: "./Songs/SAD! - XXXTENTACION.mp3", cover: "./Covers/SAD!.jpg" },
  { title: "Safari", name: "Serena", source: "./Songs/Safari - Serena.mp3", cover: "./Covers/Safari.jpg" },
  { title: "Sapphire", name: "Ed Sheeran", source: "./Songs/Sapphire - Ed Sheeran.mp3", cover: "./Covers/Sapphire.jpg" },
  { title: "Savannah", name: "Diviners", source: "./Songs/Savannah - Diviners.mp3", cover: "./Covers/Savannah.jpg" },
  { title: "Say You Won't Let Go", name: "James Arthur", source: "./Songs/Say You Won't Let Go - James Arthur.mp3", cover: "./Covers/Say You Won't Let Go.jpg" },
  { title: "Self Control", name: "Laura Branigan", source: "./Songs/Self Control - Laura Branigan.mp3", cover: "./Covers/Self Control.jpg" },
  { title: "September Trees", name: "memyself", source: "./Songs/September Trees - memyself.mp3", cover: "./Covers/September Trees.jpg" },
  { title: "Señorita", name: "Shawn Mendes, Camila Cabello", source: "./Songs/Señorita - Shawn Mendes, Camila Cabello.mp3", cover: "./Covers/Señorita.jpg" },
  { title: "Shameless", name: "Camila Cabello", source: "./Songs/Shameless - Camila Cabello.mp3", cover: "./Covers/Shameless.jpg" },
  { title: "Shape of You", name: "Ed Sheeran", source: "./Songs/Shape of You - Ed Sheeran.mp3", cover: "./Covers/Shape of You.jpg" },
  { title: "She Doesn't Mind", name: "TommyMuzzic", source: "./Songs/She Doesn't Mind - TommyMuzzic.mp3", cover: "./Covers/She Doesn't Mind.jpg" },
  { title: "Sink Or Swim", name: "OneRepublic", source: "./Songs/Sink Or Swim - OneRepublic.mp3", cover: "./Covers/Sink Or Swim.jpg" },
  { title: "Sit Still, Look Pretty", name: "Daya", source: "./Songs/Sit Still, Look Pretty - Daya.mp3", cover: "./Covers/Sit Still, Look Pretty.jpg" },
  { title: "Skinny Love", name: "Alex Grey", source: "./Songs/Skinny Love - Alex Grey.mp3", cover: "./Covers/Skinny Love.jpg" },
  { title: "Someday", name: "OneRepublic", source: "./Songs/Someday - OneRepublic.mp3", cover: "./Covers/Someday.jpg" },
  { title: "Someone to Rely On", name: "Gamma Skies", source: "./Songs/Someone to Rely On - Gamma Skies.mp3", cover: "./Covers/Someone to Rely On.jpg" },
  { title: "Something Just Like This", name: "The Chainsmokers", source: "./Songs/Something Just Like This - The Chainsmokers.mp3", cover: "./Covers/Something Just Like This.jpg" },
  { title: "Standing Still", name: "Joakim Molitor", source: "./Songs/Standing Still - Joakim Molitor.mp3", cover: "./Covers/Standing Still.jpg" },
  { title: "Stars Will Align", name: "Kygo, Imagine Dragons", source: "./Songs/Stars Will Align - Kygo, Imagine Dragons.mp3", cover: "./Covers/Stars Will Align.jpg" },
  { title: "Stargazing", name: "Kygo", source: "./Songs/Stargazing - Kygo.mp3", cover: "./Covers/Stargazing.jpg" },
  { title: "Starving", name: "Hailee Steinfeld, Grey,  Zedd", source: "./Songs/Starving - Hailee Steinfeld, Grey,  Zedd.mp3", cover: "./Covers/Starving.jpg" },
  { title: "Stay", name: "Gracie Abrams", source: "./Songs/Stay - Gracie Abrams.mp3", cover: "./Covers/Stay.jpg" },
  { title: "Stereo Hearts", name: "Gym Class Heroes", source: "./Songs/Stereo Hearts - Gym Class Heroes.mp3", cover: "./Covers/Stereo Hearts.jpg" },
  { title: "Stereo Love", name: "Edward Maya", source: "./Songs/Stereo Love - Edward Maya.mp3", cover: "./Covers/Stereo Love.jpg" },
  { title: "Stitches", name: "Shawn Mendes", source: "./Songs/Stitches - Shawn Mendes.mp3", cover: "./Covers/Stitches.jpg" },
  { title: "Stranger Things", name: "Kygo", source: "./Songs/Stranger Things - Kygo.mp3", cover: "./Covers/Stranger Things.jpg" },
  { title: "Sugar", name: "Maroon 5", source: "./Songs/Sugar - Maroon 5.mp3", cover: "./Covers/Sugar.jpg" },
  { title: "Summer Bath", name: "Wahidul Choudhury", source: "./Songs/Summer Bath - Wahidul Choudhury.mp3", cover: "./Covers/Summer Bath.jpg" },
  { title: "Sunroof", name: "Nicky Youre", source: "./Songs/Sunroof - Nicky Youre.mp3", cover: "./Covers/Sunroof.jpg" },
  { title: "Superhero In My Sleep", name: "Rival", source: "./Songs/Superhero In My Sleep - Rival.mp3", cover: "./Covers/Superhero In My Sleep.jpg" },
  { title: "Sweet but Psycho", name: "Ava Max", source: "./Songs/Sweet but Psycho - Ava Max.mp3", cover: "./Covers/Sweet but Psycho.jpg" },
  { title: "Symphony", name: "Clean Bandit", source: "./Songs/Symphony - Clean Bandit.mp3", cover: "./Covers/Symphony.jpg" },
  { title: "Tarantella", name: "Gabry Ponte", source: "./Songs/Tarantella - Gabry Ponte.mp3", cover: "./Covers/Tarantella.jpg" },
  { title: "Tattoo", name: "Loreen", source: "./Songs/Tattoo - Loreen.mp3", cover: "./Covers/Tattoo.jpg" },
  { title: "Telepatia", name: "Farizki", source: "./Songs/Telepatia - Farizki.mp3", cover: "./Covers/Telepatia.jpg" },
  { title: "Tell Me Why", name: "Loote", source: "./Songs/Tell Me Why - Loote.mp3", cover: "./Covers/Tell Me Why.jpg" },
  { title: "That's So True", name: "Gracie Abrams", source: "./Songs/That's So True - Gracie Abrams.mp3", cover: "./Covers/That's So True.jpg" },
  { title: "The Greatest", name: "Sia", source: "./Songs/The Greatest - Sia.mp3", cover: "./Covers/The Greatest.jpg" },
  { title: "The Great Escape", name: "Josie Edwards", source: "./Songs/The Great Escape - Josie Edwards.mp3", cover: "./Covers/The Great Escape.jpg" },
  { title: "The Middle", name: "Zedd", source: "./Songs/The Middle - Zedd.mp3", cover: "./Covers/The Middle.jpg" },
  { title: "This Feeling", name: "The Chainsmokers", source: "./Songs/This Feeling - The Chainsmokers.mp3", cover: "./Covers/This Feeling.jpg" },
  { title: "Things I Love", name: "Lvly", source: "./Songs/Things I Love - Lvly.mp3", cover: "./Covers/Things I Love.jpg" },
  { title: "this is what heartbreak feels like", name: "JVKE", source: "./Songs/this is what heartbreak feels like - JVKE.mp3", cover: "./Covers/this is what heartbreak feels like.jpg" },
  { title: "Thumbs", name: "Sabrina Carpenter", source: "./Songs/Thumbs - Sabrina Carpenter.mp3", cover: "./Covers/Thumbs.jpg" },
  { title: "Thunder", name: "Gabry Ponte", source: "./Songs/Thunder - Gabry Ponte.mp3", cover: "./Covers/Thunder.jpg" },
  { title: "Tick Tock", name: "Clean Bandit", source: "./Songs/Tick Tock - Clean Bandit.mp3", cover: "./Covers/Tick Tock.jpg" },
  { title: "TiK ToK", name: "EQRIC", source: "./Songs/TiK ToK - EQRIC.mp3", cover: "./Covers/TiK ToK.jpg" },
  { title: "Too Late", name: "OmgLoSteve", source: "./Songs/Too Late - OmgLoSteve.mp3", cover: "./Covers/Too Late.jpg" },
  { title: "Tutsak", name: "Sefo", source: "./Songs/Tutsak - Sefo.mp3", cover: "./Covers/Tutsak.jpg" },
  { title: "UP", name: "INNA", source: "./Songs/UP - INNA.mp3", cover: "./Covers/UP.jpg" },
  { title: "Used To", name: "Sandro Cavazza", source: "./Songs/Used To - Sandro Cavazza.mp3", cover: "./Covers/Used To.jpg" },
  { title: "Wake Me Up In Paris", name: "Anthony Keyrouz", source: "./Songs/Wake Me Up In Paris - Anthony Keyrouz.mp3", cover: "./Covers/Wake Me Up In Paris.jpg" },
  { title: "Waiting", name: "Vicetone", source: "./Songs/Waiting - Vicetone.mp3", cover: "./Covers/Waiting.jpg" },
  { title: "Walk Thru Fire", name: "Vicetone", source: "./Songs/Walk Thru Fire - Vicetone.mp3", cover: "./Covers/Walk Thru Fire.jpg" },
  { title: "Way Back Home", name: "Sam Feldt", source: "./Songs/Way Back Home - Sam Feldt.mp3", cover: "./Covers/Way Back Home.jpg" },
  { title: "we can't be friends", name: "Ariana Grande", source: "./Songs/we can't be friends - Ariana Grande.mp3", cover: "./Covers/we can't be friends.jpg" },
  { title: "We Don't Talk Anymore", name: "Charlie Puth", source: "./Songs/We Don't Talk Anymore - Charlie Puth.mp3", cover: "./Covers/We Don't Talk Anymore.jpg" },
  { title: "We Go Down Together", name: "BLAEKER", source: "./Songs/We Go Down Together - BLAEKER.mp3", cover: "./Covers/We Go Down Together.jpg" },
  { title: "We Should Be Sorry", name: "Axel Johansson", source: "./Songs/We Should Be Sorry - Axel Johansson.mp3", cover: "./Covers/We Should Be Sorry.jpg" },
  { title: "What If", name: "Johnny Orlando", source: "./Songs/What If - Johnny Orlando.mp3", cover: "./Covers/What If.jpg" },
  { title: "Whatever", name: "Kygo, Ava Max", source: "./Songs/Whatever - Kygo, Ava Max.mp3", cover: "./Covers/Whatever.jpg" },
  { title: "When You're Lonely", name: "Hoang", source: "./Songs/When You_re Lonely - Hoang.mp3", cover: "./Covers/When You're Lonely.jpg" },
  { title: "Where Are You Now", name: "Lost Frequencies", source: "./Songs/Where Are You Now - Lost Frequencies.mp3", cover: "./Covers/Where Are You Now.jpg" },
  { title: "Wilder", name: "Gamma Skies", source: "./Songs/Wilder - Gamma Skies.mp3", cover: "./Covers/Wilder.jpg" },
  { title: "Without Me", name: "Halsey", source: "./Songs/Without Me - Halsey.mp3", cover: "./Covers/Without Me.jpg" },
  { title: "Wrap Me In Plastic", name: "CHROMANCE", source: "./Songs/Wrap Me In Plastic - CHROMANCE.mp3", cover: "./Covers/Wrap Me In Plastic.jpg" },
  { title: "You should be sad", name: "Halsey", source: "./Songs/You should be sad - Halsey.mp3", cover: "./Covers/You should be sad.jpg" },
  { title: "Young", name: "The Chainsmokers", source: "./Songs/Young - The Chainsmokers.mp3", cover: "./Covers/Young.jpg" },
  { title: "Şehrin Yolu", name: "Feride Hilal Akın", source: "./Songs/Şehrin Yolu - Feride Hilal Akın.mp3", cover: "./Covers/Şehrin Yolu.jpg" },
  { title: "Їде дах", name: "Klavdia Petrivna", source: "./Songs/Їде дах - Klavdia Petrivna.mp3", cover: "./Covers/Їде дах.jpg" },
  { title: "Дикая львица", name: "ALEX", source: "./Songs/Дикая львица - ALEX.mp3", cover: "./Covers/Дикая львица.jpg" }
];